export const quizQuestions = {
  stress: {
    title: "Am I Stressed?",
    questions: [
      "How often do you find it difficult to relax and unwind after a long day?",
      "Are you often overwhelmed by the number of tasks and responsibilities on your plate?",
      "Do you frequently experience physical symptoms of stress like headaches, muscle tension, or digestive issues?",
      "Are you prone to irritability and mood swings?",
      "Do you have trouble focusing or making decisions when stressed?",
      "Have you noticed changes in your eating or sleeping patterns when under stress?",
      "Is your stress level affecting your relationships with family and friends?",
      "Do you use healthy coping strategies, like exercise or meditation, to manage stress?",
      "Are you able to set boundaries and say no when necessary?",
      "How would you rate your overall stress level on a scale of 1 to 10?",
    ],
  },
  anxious: {
    title: "Am I Anxious?",
    questions: [
      "Do you feel nervous, restless, or tense?",
      "Are you easily startled?",
      "Do you have trouble concentrating?",
      "Do you have trouble falling asleep or staying asleep?",
      "Do you feel tired all the time?",
      "Do you experience muscle tension, aches, or soreness?",
      "Do you experience frequent headaches?",
      "Do you experience frequent stomachaches or digestive issues?",
      "Do you experience irritability?",
      "Do you experience sweating, trembling, or shaking?",
    ],
  },
  sad: {
    title: "Am I Sad or Depressed?",
    questions: [
      "Do you feel sad or hopeless?",
      "Do you feel irritable or angry?",
      "Do you feel guilty or worthless?",
      "Do you feel anxious or restless?",
      "Do you feel empty or numb?",
      "Do you feel like you have no energy?",
      "Do you feel like you can’t concentrate or make decisions?",
      "Do you feel like you can’t sleep or sleep too much?",
      "Do you feel like you can’t eat or eat too much?",
      "Do you feel like you can’t enjoy things you used to enjoy?",
    ],
  },
  sleep: {
    title: "How am i sleeping?",
    questions: [
      "Do you feel tired during the day?",
      "Do you have trouble concentrating?",
      "Do you have trouble remembering things?",
      "Do you have trouble making decisions?",
      "Do you have trouble controlling your emotions?",
      "Do you feel irritable or angry?",
      "Do you feel depressed?",
      "Do you feel anxious?",
      "Do you feel like you need a nap?",
      "Do you fall asleep in less than 5 minutes?",
    ],
  },
  happiness: {
    title: "How happy am I?",
    questions: [
      "I feel happy.",
      "I feel like I am enjoying life.",
      "I feel hopeful about the future.",
      "I feel like I am in control of my life.",
      "I feel like I am making progress towards my goals.",
      "I feel like I am respected by others.",
      "I feel like I am loved by others.",
      "I feel like I am a good person.",
      "I feel like I am a valuable person.",
      "I feel like I am a confident person.",
    ],
  },
  workplace: {
    title: "How stressed am I at work?",
    questions: [
      "I feel like I am in control of my workload.",
      "I feel like I am in control of my schedule.",
      "I feel like I am in control of my work environment.",
      "I feel like I am in control of my work relationships.",
      "I feel like I am in control of my work-life balance.",
      "I feel like I am in control of my career path.",
      "I feel like I am in control of my career growth.",
      "I feel like I am in control of my career development.",
      "I feel like I am in control of my career goals.",
      "I feel like I am in control of my career satisfaction.",
    ],
  },
};
